### PR TITLE
Update instructions due to the Bionic to Focal migration

### PR DESCRIPTION
**Pull request by hebasto**
This PR accommodates the recent changes:
- https://github.com/bitcoin/bitcoin/pull/21036
- https://github.com/bitcoin/bitcoin/pull/21130

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK f3bccb822af522ca25901886a287aec1ac435073 - I guess we are not needing instructions for building < 0.17

**Comment by MarcoFalke** [comment]
ACK 

Could apply the same changes here: https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-fedora.md#setting-up-the-gitian-image ?

**Comment by hebasto** [comment]
> Could apply the same changes here: https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-fedora.md#setting-up-the-gitian-image ?

Done.

**Comment by MarcoFalke** [comment]
ACK 6d330caf2dd7c51d042e806166a79832aa68e174

**Pull request merged**
