### PR TITLE
gitian setup on debian: Use ip and firewalld over ifconfig/iptables

### PR DESCRIPTION
**Pull request by MarcoFalke**
Proposed fix for #15

### CODE REVIEW

**Comment by Sjors** [comment]
Nice, will give this a try.

**Comment by fivepiece** [comment]
This network setup is working well for me on a debian 9 VM behind NAT.

**Comment by fivepiece** [comment]
I can confirm that this is working for me on a bridged (so, not NAT) debian 9 VM.  The inner container is able to reach the network.  It's likely that my 'proxmox\qemu -> NAT gitian VM -> gitian builder LXC' setup is failing because of specific NAT configs on my host.

**Comment by MarcoFalke** [comment]
@fivepiece I assume the debian 8 setup with ifconfig/iptables worked fine, previously?

**Comment by fivepiece** [comment]
I never did use debian 8, just debian 9 with the net-tools package.
This PR's change to the commands achieves the same bridge setup as those on debian 9 with firewalld instead.

**Comment by MarcoFalke** [comment]
Heh, I still can't parse your comments to determine if the situation improves after the patch.

**Comment by fivepiece** [comment]
Sorry, yes it does improve it imo.  net-tools is obsolete and this change is for the better.

**Comment by jonasschnelli** [comment]
Not sure if the migration from ip-tables to firewalld was clever,... I could only get it running with `iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE`.

**Comment by MarcoFalke** [comment]
Was that a fresh install or an upgrade from you previous debian host?

Anyway, thanks for getting the osx nightly builds run again!

**Pull request merged**
