### PR TITLE
[WIP] Updated debian vm installation to 9.x (stretch)

### PR DESCRIPTION
**Pull request by cisba**
The 8.x (jessie) is deprecated. Ref. [#12511](https://github.com/bitcoin/bitcoin/issues/12511) issue in bitcoin/bitcoin.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The host shouldn't matter and I am not aware that any host os is deprecated.

**Comment by cisba** [comment]
@MarcoFalke take a look at the issue [14176](https://github.com/bitcoin/bitcoin/pull/14176) on bitcoin/bitcoin

**Comment by cisba** [comment]
Thanks @MarcoFalke for your comment, I misunderstood initially some point in the documentation, and subsequently I had problems building with gitian on Debian 8.x (not deprecated, as you pointed out).

Anyway, for a newcomer could be more easy to use Ubuntu 18.04 (as I experienced just now).
So I will try to improve the documentation, with the aim to increase the number of potential gitian signers.

**Comment by karel-3d** [comment]
Debian has errors because debian has ancient LXC.

See this

https://gist.github.com/laanwj/c62e101bfd68718f0686926dfd10666b

(not sure if related to the PR)

**Pull request closed without merging**
